image: docker:stable

services:
    - docker:stable-dind

variables:
    REPOSITORY: "${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"
    OS: "${CI_COMMIT_REF_NAME}"

before_script:
    - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_TOKEN}"

stages:
    - cuda
    - cudnn

.cuda_base_template: &cuda_base_definition
    stage: cuda
    script:
    - VERSION="${CI_JOB_NAME:1}"
    - docker build --pull -t "${REPOSITORY}:${VERSION}-base-${OS}"
                   --label "com.nvidia.build.ref=${CI_COMMIT_SHA}"
                   --label "com.nvidia.build.id=${CI_JOB_ID}"
                   "${VERSION}/base"
    - docker build -t "${REPOSITORY}:${VERSION}-runtime-${OS}"
                   --build-arg "repository=${REPOSITORY}"
                   --label "com.nvidia.build.ref=${CI_COMMIT_SHA}"
                   --label "com.nvidia.build.id=${CI_JOB_ID}"
                   "${VERSION}/runtime"
    - docker build -t "${REPOSITORY}:${VERSION}-devel-${OS}"
                   --build-arg "repository=${REPOSITORY}"
                   "${VERSION}/devel"
    - if [[ "${NO_OS_SUFFIX}" == true ]]; then
          docker tag "${REPOSITORY}:${VERSION}-base-${OS}" "${REPOSITORY}:${VERSION}-base";
          docker tag "${REPOSITORY}:${VERSION}-runtime-${OS}" "${REPOSITORY}:${VERSION}-runtime";
          docker tag "${REPOSITORY}:${VERSION}-devel-${OS}" "${REPOSITORY}:${VERSION}-devel";
      fi
    - if [[ "${LATEST}" == true ]]; then
          docker tag "${REPOSITORY}:${VERSION}-devel-${OS}" "${REPOSITORY}:latest";
      fi
    - docker push "${REPOSITORY}"

.cudnn_template: &cudnn_definition
    stage: cudnn
    script:
    - VERSION="${CI_JOB_NAME:1}"
    - CUDA_VERSION="${CI_JOB_NAME:1:3}"
    - CUDNN_VERSION="${CI_JOB_NAME:5}"
    - docker build --pull -t "${REPOSITORY}:${VERSION}-runtime-${OS}"
                   --build-arg "repository=${REPOSITORY}"
                   "${CUDA_VERSION}/runtime/${CUDNN_VERSION}"
    - docker build --pull -t "${REPOSITORY}:${VERSION}-devel-${OS}"
                   --build-arg "repository=${REPOSITORY}"
                   "${CUDA_VERSION}/devel/${CUDNN_VERSION}"
    - if [[ "${NO_OS_SUFFIX}" == true ]]; then
          docker tag "${REPOSITORY}:${VERSION}-runtime-${OS}" "${REPOSITORY}:${VERSION}-runtime";
          docker tag "${REPOSITORY}:${VERSION}-devel-${OS}" "${REPOSITORY}:${VERSION}-devel";
      fi
    - docker push "${REPOSITORY}"

v9.2:
    <<: *cuda_base_definition

v9.2-cudnn7:
    <<: *cudnn_definition
